hw2
made-mlops-2022/latskov_aleksei pull request #2
Opened 2022-11-25 19:16 UTC by Alexcei

1. Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict [3 / 3]
2. Напишите endpoint /health, который должен возвращать 200, если ваша модель готова к работе [1 / 1]
3. Напишите unit тест [0 / 3] юнит тесты написал, но не получилось запустить.
4. Напишите скрипт, который будет делать запросы к вашему сервису [2 / 2].
5. Напишите Dockerfile... [4 / 4].
6. Опубликуйте образ [2 /2] https://hub.docker.com/repository/docker/alexcei64/online_inference.
7. Опишите в README.md корректные команды docker pull/run [1 / 1].
8. Проведите самооценку [1 / 1].

Дополнительная часть:
1. Ваш сервис скачивает модель из S3... [0 / 2]
2. Оптимизируйте размер docker image. [1 / 2] Использовал slim версию родительского образа, что уменьшило размер получившегося в 2 раза.
3. Сделайте валидацию входных данных [2 / 2] Использовал pydantic.

Итого 17

2022-12-19 03:54 UTC, SVizor42 commented on ml_project/online_inference/src/app.py
> +    print('startup done')
Нужно использовать логирование вместо принтов

2022-12-19 04:01 UTC, SVizor42 commented on ml_project/online_inference/src/predict.py
> +        print(error)
Зачем загружать модель при каждом вызове функции? Это выполняется при старте сервиса

2022-12-19 04:02 UTC, SVizor42 commented on ml_project/online_inference/src/predict.py
> +    predict()
В целом непонятна логика этого модуля. По сути она дублирует код эндпойнта `/predict`, за исключение чтения и записи данных.

2022-12-19 04:09 UTC, SVizor42 requested changes
Нужно внести правки по комментариям. На мой взгляд, проект для онлайн инференса содержит избыточные модули (например, `evaluate.py`).
По поводу доп пункта с валидацией входных данных -вижу только модели, валидаторов не обнаружил.

2022-12-24 22:48 UTC, Alexcei commented on ml_project/online_inference/src/app.py
> +    print('startup done')
Добавил логирование

2022-12-24 22:49 UTC, Alexcei commented on ml_project/online_inference/src/predict.py
> +    predict()
Избавился от модуля "predict.py"

2022-12-24 22:50 UTC, Alexcei commented on ml_project/online_inference/src/predict.py
> +        print(error)
Переиспользовал загруженную модель из модуля app.py

2022-12-24 22:56 UTC, Alexcei commented
1. На мой взгляд, проект для онлайн инференса содержит избыточные модули (например, evaluate.py).
`Убрал "evaluate.py"`
2. По поводу доп пункта с валидацией входных данных -вижу только модели, валидаторов не обнаружил.
`Валидация с помощью моделей ввода/вывода в ф-и "predict_once" модуля "app.py"`
3. Нужно добавить метку работы hw2.
`Добавил метку`

2022-12-25 08:42 UTC, SVizor42 approved these changes
Хорошо.

**Сумма: 17 баллов**

Ветку можно сливать.

2022-12-25 15:41 UTC, merged